import { Routes } from '@angular/router';
import { HomeComponent } from './components/home/home.component';
import { LoginComponent } from './components/login/login.component';
import { LoginAdministratorComponent } from './components/login-administrator/login-administrator.component';
import { LoginHostComponent } from './components/login-host/login-host.component';
import { LoginUserComponent } from './components/login-user/login-user.component';
import { RegisterComponent } from './components/register/register.component';
import { RegisterAdministratorComponent } from './components/register-administrator/register-administrator.component';
import { RegisterHostComponent } from './components/register-host/register-host.component';
import { RegisterUserComponent } from './components/register-user/register-user.component';
import { MyReservationsComponent } from './components/my-reservations/my-reservations.component';
import { ChangePasswordAdminComponent } from './components/change-password-admin/change-password-admin.component';
import { ChangePasswordHostComponent } from './components/change-password-host/change-password-host.component';
import { ChangePasswordUserComponent } from './components/change-password-user/change-password-user.component';
import { CreateAccommodationComponent } from './components/create-accommodation/create-accommodation.component';
import { CreateCityComponent } from './components/create-city/create-city.component';
import { CreateDepartmentComponent } from './components/create-department/create-department.component';
import { CreateReservationComponent } from './components/create-reservation/create-reservation.component';
import { EditProfileAdminComponent } from './components/edit-profile-admin/edit-profile-admin.component';
import { EditProfileHostComponent } from './components/edit-profile-host/edit-profile-host.component';
import { EditProfileUserComponent } from './components/edit-profile-user/edit-profile-user.component';
import { CreateRoleComponent } from './components/create-role/create-role.component';
import { CreateServiceComponent } from './components/create-service/create-service.component';
import { ManagementDepartmentComponent } from './components/management-department/management-department.component';
import { ManagementCityComponent } from './components/management-city/management-city.component';
import { ManagementServiceComponent } from './components/management-service/management-service.component';
import { ManagementRoleComponent } from './components/management-role/management-role.component';
import { ManagementAccommodationsComponent } from './components/management-accommodations/management-accommodations.component';
import { EditCityComponent } from './components/edit-city/edit-city.component';
import { EditDepartmentComponent } from './components/edit-department/edit-department.component';
import { EditAccommodationComponent } from './components/edit-accommodation/edit-accommodation.component';
import { EditServiceComponent } from './components/edit-service/edit-service.component';
import { EditRoleComponent } from './components/edit-role/edit-role.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'registerAdmin', component: RegisterAdministratorComponent },
  { path: 'registerUser', component: RegisterUserComponent },
  { path: 'registerHost', component: RegisterHostComponent },
  { path: 'loginHost', component: LoginHostComponent },
  { path: 'loginAdmin', component: LoginAdministratorComponent },
  { path: 'loginUser', component: LoginUserComponent },
  { path: 'myReservations', component: MyReservationsComponent },
  { path: 'changePasswordAdmin', component: ChangePasswordAdminComponent },
  { path: 'changePasswordHost', component: ChangePasswordHostComponent },
  { path: 'changePasswordUser', component: ChangePasswordUserComponent },
  { path: 'createAccommodation', component: CreateAccommodationComponent },
  { path: 'createCity', component: CreateCityComponent },
  { path: 'createDepartment', component: CreateDepartmentComponent },
  { path: 'createReservation', component: CreateReservationComponent },
  { path: 'editProfileAdmin', component: EditProfileAdminComponent },
  { path: 'editProfileHost', component: EditProfileHostComponent },
  { path: 'editProfileUser', component: EditProfileUserComponent },
  { path: 'createRole', component: CreateRoleComponent },
  { path: 'createService', component: CreateServiceComponent },
  { path: 'managementDepartment', component: ManagementDepartmentComponent },
  { path: 'managementCity', component: ManagementCityComponent },
  { path: 'managementService', component: ManagementServiceComponent },
  { path: 'managementRole', component: ManagementRoleComponent },
  { path: 'managementAccommodations', component: ManagementAccommodationsComponent },
  { path: 'editCity', component: EditCityComponent },
  { path: 'editDepartment', component: EditDepartmentComponent },
  { path: 'editAccommodation', component: EditAccommodationComponent },
  { path: 'editService', component: EditServiceComponent },
  { path: 'editRole', component: EditRoleComponent },
];